// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBG89F51QvMYkMI44z9q7o6Vq3Om4ktvM',
    appId: '1:260518873568:web:6a49e7a1b4875578b90385',
    messagingSenderId: '260518873568',
    projectId: 'fir-app-d9b29',
    authDomain: 'fir-app-d9b29.firebaseapp.com',
    storageBucket: 'fir-app-d9b29.appspot.com',
    measurementId: 'G-K7NCDCBX29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk6i5kCNbzsMoJ0urc0p_efj7wOZJoFRM',
    appId: '1:260518873568:android:bbe5c18f42258ddcb90385',
    messagingSenderId: '260518873568',
    projectId: 'fir-app-d9b29',
    storageBucket: 'fir-app-d9b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_aHCv3VnnF9-PoGJTsduMRAxX_ceW82U',
    appId: '1:260518873568:ios:3b0daed1c2d6a51ab90385',
    messagingSenderId: '260518873568',
    projectId: 'fir-app-d9b29',
    storageBucket: 'fir-app-d9b29.appspot.com',
    iosBundleId: 'com.example.signupPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_aHCv3VnnF9-PoGJTsduMRAxX_ceW82U',
    appId: '1:260518873568:ios:9018b4ebfac2a4fdb90385',
    messagingSenderId: '260518873568',
    projectId: 'fir-app-d9b29',
    storageBucket: 'fir-app-d9b29.appspot.com',
    iosBundleId: 'com.example.signupPage.RunnerTests',
  );
}
